include $(APPDIR)/Make.defs

# Ultrasound test! built-in application info

PROGNAME  = $(CONFIG_EXAMPLES_ULTRASOUND_PROGNAME)
PRIORITY  = $(CONFIG_EXAMPLES_ULTRASOUND_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_ULTRASOUND_STACKSIZE)
MODULE    = $(CONFIG_EXAMPLES_ULTRASOUND)

# Ultrasound test! Example

MAINSRC = ultrasound_main.c

include $(APPDIR)/Application.mk
